apiVersion: apps/v1
kind: Deployment
metadata:
  name: deep-microservice-subscription-deployment
  labels:
    app: deep-microservice-subscription
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deep-microservice-subscription
  template:
    metadata:
      labels:
        app: deep-microservice-subscription
    spec:
      containers:
      - name: deep-microservice-subscription
        image: thinkdeeptech/deep-microservice-subscription:latest
        ports:
        - containerPort: 4004
        env:
          - name: PREDECOS_AUTH_AUDIENCE
            value: "$PREDECOS_AUTH_AUDIENCE"
          - name: PREDECOS_AUTH_JWKS_URI
            value: "$PREDECOS_AUTH_JWKS_URI"
          - name: PREDECOS_AUTH_ISSUER
            value: "$PREDECOS_AUTH_ISSUER"
          - name: PREDECOS_MICROSERVICE_ANALYSIS_URL
            value: "$PREDECOS_MICROSERVICE_ANALYSIS_URL"
          - name: PREDECOS_MICROSERVICE_COLLECTION_URL
            value: "$PREDECOS_MICROSERVICE_COLLECTION_URL"
          - name: PREDECOS_MICROSERVICE_CONFIGURATION_URL
            value: "$PREDECOS_MICROSERVICE_CONFIGURATION_URL"
          - name: PREDECOS_KAFKA_HOST
            value: "$PREDECOS_KAFKA_HOST"
          - name: PREDECOS_KAFKA_PORT
            value: "$PREDECOS_KAFKA_PORT"
          - name: NODE_ENV
            value: "$NODE_ENV"
      imagePullSecrets:
        - name: docker-secret
