plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: /home/hayden/dev/thinkdeep/.yarn/releases/yarn-berry.js

nmHoistingLimits: "workspaces"

nodeLinker: node-modules
