apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ printf "%s-deployment" .Release.Name | quote}}
  labels:
    app: "deep-microservice-subscription"
    app.kubernetes.io/managed-by: "helm"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: "deep-microservice-subscription"
  template:
    metadata:
      labels:
        app: "deep-microservice-subscription"
    spec:
      containers:
      - name: "deep-microservice-subscription"
        image: "thinkdeeptech/deep-microservice-subscription:latest"
        envFrom:
        - configMapRef:
            name: "deep-microservice-subscription-config-map"
        - secretRef:
            name: "deep-microservice-subscription-secrets"
        ports:
        - containerPort: 4004
        imagePullPolicy: "Always"
      imagePullSecrets:
        - name: "docker-secret"
