apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ printf "%s-deep-microservice-subscription-deployment" .Release.Name | quote }}
  namespace: {{ .Values.global.namespace | quote }}
  labels:
    app: {{ printf "%s-deep-microservice-subscription-deployment" .Release.Name | quote }}
    app.kubernetes.io/managed-by: "helm"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ printf "%s-deep-microservice-subscription-deployment" .Release.Name | quote }}
  template:
    metadata:
      labels:
        app: {{ printf "%s-deep-microservice-subscription-deployment" .Release.Name | quote }}
    spec:
      containers:
      - name: "deep-microservice-subscription"
        image: "thinkdeeptech/deep-microservice-subscription:latest"
        envFrom:
        - configMapRef:
            name: {{ printf "%s-deep-microservice-subscription-environment" .Release.Name | quote }}
        - secretRef:
            name: {{ printf "%s-deep-microservice-subscription-secret" .Release.Name | quote }}
        - secretRef:
          {{ if not .Values.global.microservice.url.secretName }}
            name: {{ printf "%s-deep-microservice-subscription-microservice-url-secret" .Release.Name | quote }}
          {{ else }}
            name: {{ printf "%s" .Values.global.microservice.url.secretName | quote }}
          {{ end }}
        - secretRef:
          {{ if not .Values.global.microservice.auth.secretName }}
            name: {{ printf "%s-deep-microservice-subscription-auth-secret" .Release.Name | quote }}
          {{ else }}
            name: {{ printf "%s" .Values.global.microservice.auth.secretName | quote }}
          {{ end }}
        {{ if .Values.global.kafka.secretName }}
        - secretRef:
            name: {{ printf "%s" .Values.global.kafka.secretName | quote }}
        {{ end }}

        ports:
        - containerPort: {{ .Values.graphql.port }}
        imagePullPolicy: "Always"
      imagePullSecrets:
        - name: "docker-secret"
