{{ if not .Values.global.microservice.url.secretName }}
apiVersion: "v1"
kind: "Secret"
metadata:
    name: {{ printf "%s-deep-microservice-subscription-microservice-url-secret" .Release.Name | quote }}
    namespace: {{ .Values.global.namespace | quote }}
data:
    PREDECOS_MICROSERVICE_ANALYSIS_URL: {{ printf "%s" (required "A url pointing to the analysis microservice is required if a config map is not specified." .Values.microservice.analysis.url) | b64enc | quote }}
    PREDECOS_MICROSERVICE_COLLECTION_URL: {{ printf "%s" (required "A url pointing to the collection microservice is required if a config map is not specified." .Values.microservice.collection.url) | b64enc | quote }}
    PREDECOS_MICROSERVICE_CONFIGURATION_URL: {{ printf "%s" (required "A url pointing to the configuration microservice is required if a config map is not specified." .Values.microservice.configuration.url) | b64enc | quote }}
{{ end }}