apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-deep-microservice-subscription-service" .Release.Name | quote }}
  namespace: {{ .Values.global.namespace | quote }}
  annotations:
    # No TLS port annotation needed since 443 is assumed for HTTPS when another TLS option annotation is given.
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "c0498386-47b7-4c82-9938-7d5e8734469a"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "round_robin"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
spec:
  type: LoadBalancer
  selector:
    app: {{ printf "%s-deep-microservice-subscription-deployment" .Release.Name | quote }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.graphql.port }}
    - name: https
      protocol: TCP
      port: 443
      targetPort: {{ .Values.graphql.port }}