apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ printf "%s-deep-microservice-configuration-deployment" .Release.Name | quote }}
  namespace: {{ .Values.global.namespace | quote }}
  labels:
    app: {{ printf "%s-deep-microservice-configuration-deployment" .Release.Name | quote }}
    app.kubernetes.io/managed-by: "helm"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ printf "%s-deep-microservice-configuration-deployment" .Release.Name | quote }}
  template:
    metadata:
      labels:
        app: {{ printf "%s-deep-microservice-configuration-deployment" .Release.Name | quote }}
    spec:
      containers:
      - name: "deep-microservice-configuration"
        image: "thinkdeeptech/deep-microservice-configuration:latest"
        envFrom:
        - configMapRef:
            name: {{ printf "%s-deep-microservice-configuration-config-map" .Release.Name | quote }}
        - secretRef:
            name: {{ printf "%s-deep-microservice-configuration-secret" .Release.Name | quote }}
        ports:
        - containerPort: {{ .Values.port }}
        imagePullPolicy: "Always"
      imagePullSecrets:
        - name: "docker-secret"
