# TODO: This needs to be reintroduced when DNS is added.
# apiVersion: "v1"
# kind: "Service"
# metadata:
#   name: {{ printf "%s-service" .Release.Name | quote}}
# spec:
#   selector:
#     app: "deep-microservice-configuration"
#   ports:
#     - protocol: "TCP"
#       port: 4003