version: 2.1

orbs:
    browser-tools: circleci/browser-tools@1.2.2
    kubernetes: circleci/kubernetes@1.0.2

commands:
    install_command:
      steps:
        - run: yarn install
        - run: yarn add -W apollo-datasource-mongodb && yarn add -W mongodb

    test_command:
      steps:
        - run: yarn run tests

    build_command:
      steps:
        - run: yarn run build

    deploy_command:
      steps:
        - run: curl -sL https://firebase.tools | bash
        - run: firebase --token $FIREBASE_TOKEN deploy

jobs:
    build:
      docker:
          - image: 'cimg/node:14.17.6'

      working_directory: ~/project

      steps:
          - browser-tools/install-browser-tools
          - checkout
          - install_command
          - test_command
          - build_command

    deploy:
      docker:
          - image: 'cimg/node:14.17.6'

      working_directory: ~/project

      steps:
          - checkout
          - install_command
          - build_command
          - deploy_command


workflows:

  version: 2

  build_and_deploy_if_master:

    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
