version: 2
orbs:
    browser-tools: circleci/browser-tools@1.2.2
jobs:
    build:
        docker:
            - image: 'cimg/node:13.12-browser'

        working_directory: ~/repo

        steps:
            - browser-tools/install-browser-tools

            - checkout

            - save_cache:
                paths:
                    - null
                key: v1-dependencies-{{ checksum "package.json" }}

            # Download and cache dependencies
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}

            - run: sudo apt-get install python3

            - run: sudo apt-get install python3-pip

            - run: sudo pip3 install pytest

            - run: alias python=python3

            - run: echo "Node Version\n"

            - run: node --version

            - run: yarn run setup

            - run: yarn run tests