version: 2.1

orbs:
    browser-tools: circleci/browser-tools@1.2.2

jobs:
    install:
        docker:
          - image: 'cimg/node:14.17.6'

        working_directory: ~/project

        steps:

          - checkout

          - run:
            name: Install Dependencies
            command: yarn install
          - run:
            name: Add Missing Dependencies
            command: yarn add -W apollo-datasource-mongodb && yarn add -W mongodb

          - save_cache:
            key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
            paths:
              - ~/cache

    test:
        docker:
          - image: 'cimg/node:14.17.6'

        working_directory: ~/project

        steps:

          - restore_cache:
            keys: v1-repo-{{ .Environment.CIRCLE_SHA1 }}

          - run:
            name: Run Tests
            command: yarn run tests

    build:
      docker:
          - image: 'cimg/node:14.17.6'

      working_directory: ~/project

      steps:

          - restore_cache:
            keys: v1-repo-{{ .Environment.CIRCLE_SHA1 }}

          run:
            name: Perform Build
            command: yarn run build

    deploy:
      docker:
          - image: 'cimg/node:14.17.6'

      working_directory: ~/project

      steps:
          - restore_cache:
            key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}

          - run:
              name: Fetch and Install Firebase
              command: curl -sL https://firebase.tools | bash

          - run:
              name: Perform Deployment
              command: firebase --token $FIREBASE_TOKEN deploy


workflows:

  version: 2

  build:
    jobs:
      - install
      - test:
        requires:
          - install
      - build:
        requires:
          - install

  deploy:
    jobs:
      - install
      - build:
        requires:
          - install
      - deploy:
        requires:
          - build

        filters:
          branches:
            only:
              master

# jobs:
#     deploy:
#         docker:
#             - image: 'cimg/node:14.17.6'

#         working_directory: ~/repo

#         steps:

#             - checkout

#             - run: yarn install --force

#             - run: yarn run build

#             - run: curl -sL https://firebase.tools | bash

#             - run: which firebase

#             - run: firebase --token $FIREBASE_TOKEN deploy

#     build:
#         docker:
#             - image: 'cimg/node:14.17.6-browsers'

#         working_directory: ~/repo

#         steps:
#             - browser-tools/install-browser-tools

#             - checkout

#             - run: node --version

#             - run: yarn --version

#             - run: yarn install --force

#             # TODO: There's something wrong with the yarn install above. It seems to avoid installation of apollo-datasource-mongodb as
#             # well as mongodb itself. This is a patch solution, but isn't scalable. After build fix, troubleshoot.
#             - run: yarn add -W apollo-datasource-mongodb

#             - run: yarn add -W mongodb

#             - run: yarn run tests

#             - run: yarn run build

# workflows:

#   version: 2

#   deploy:

#     jobs:

#       - build

#       - deploy:

#           requires:

#             - build

#           filters:

#             branches:

#               only: master