version: 2.1

orbs:
    browser-tools: circleci/browser-tools@1.2.4
    kubernetes: circleci/kubernetes@1.3.0
    k8s: digitalocean/k8s@0.1.1
    helm: circleci/helm@1.2.0

commands:
    install_monorepo:
      steps:
        - run: yarn install
        - run: yarn add -W apollo-datasource-mongodb && yarn add -W mongodb && yarn add -W @rollup/plugin-graphql

    login_docker:
      steps:
        - run: echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin

    test_monorepo:
      steps:
        - run: yarn run tests

    build_ui_command:
      steps:
        - run: yarn run build

    deploy_ui_command:
      steps:
        - run: curl -sL https://firebase.tools | bash
        - run: firebase --token $FIREBASE_TOKEN deploy

jobs:

    build_and_deploy_microservice_analysis:
      docker:
        - image: 'cimg/base:stable'

      working_directory: ~/project

      steps:
        - checkout
        - setup_remote_docker:
            version: 20.10.7
        - login_docker
        - k8s/install
        - k8s/initialize:
            cluster: predecos-kubernetes-cluster
        - run:
            command: docker build -t thinkdeeptech/deep-microservice-analysis:${CIRCLE_BUILD_NUM} -t thinkdeeptech/deep-microservice-analysis:latest .
            working_directory: ./packages/deep-microservice-analysis
        - run: docker push thinkdeeptech/deep-microservice-analysis:${CIRCLE_BUILD_NUM}
        - run: docker push thinkdeeptech/deep-microservice-analysis:latest
        - helm/install-helm-client:
            version: v3.7.2
        - run:
            name: Download project dependencies
            command: helm dependency update
            working_directory: ./packages/deep-microservice-analysis
        - helm/upgrade-helm-chart:
            chart: "./packages/deep-microservice-analysis"
            helm-version: "v3.7.2"
            namespace: "default"
            recreate-pods: true
            release-name: "deep-microservice-analysis-latest"
            values-to-override: "mongodb.auth.rootUser=$MONGODB_USERNAME,mongodb.auth.rootPassword=$MONGODB_ROOT_PASSWORD,kafka.host=$PREDECOS_KAFKA_HOST,kafka.port=$PREDECOS_KAFKA_PORT,namespace=default,nodeEnv=$NODE_ENV"
            update-repositories: true
            wait: true

    build_and_deploy_microservice_collection:
      docker:
        - image: 'cimg/base:stable'

      working_directory: ~/project

      steps:
        - checkout
        - setup_remote_docker:
            version: 20.10.7
        - login_docker
        - k8s/install
        - k8s/initialize:
            cluster: predecos-kubernetes-cluster
        - run:
            command: docker build -t thinkdeeptech/deep-microservice-collection:${CIRCLE_BUILD_NUM} -t thinkdeeptech/deep-microservice-collection:latest .
            working_directory: ./packages/deep-microservice-collection
        - run: docker push thinkdeeptech/deep-microservice-collection:${CIRCLE_BUILD_NUM}
        - run: docker push thinkdeeptech/deep-microservice-collection:latest
        - helm/install-helm-client:
            version: v3.7.2
        - run:
            name: Download project dependencies
            command: helm dependency update
            working_directory: ./packages/deep-microservice-collection
        - helm/upgrade-helm-chart:
            chart: "./packages/deep-microservice-collection"
            helm-version: "v3.7.2"
            namespace: "default"
            recreate-pods: true
            release-name: "deep-microservice-collection-latest"
            values-to-override: "mongodb.auth.rootUser=$MONGODB_USERNAME,mongodb.auth.rootPassword=$MONGODB_ROOT_PASSWORD,kafka.host=$PREDECOS_KAFKA_HOST,kafka.port=$PREDECOS_KAFKA_PORT,twitter.bearer=$PREDECOS_TWITTER_BEARER,namespace=default,nodeEnv=$NODE_ENV"
            update-repositories: true
            wait: true

    build_and_deploy_microservice_configuration:
      docker:
        - image: 'cimg/base:stable'

      working_directory: ~/project

      steps:
        - checkout
        - setup_remote_docker:
            version: 20.10.7
        - login_docker
        - k8s/install
        - k8s/initialize:
            cluster: predecos-kubernetes-cluster
        - run:
            command: docker build -t thinkdeeptech/deep-microservice-configuration:${CIRCLE_BUILD_NUM} -t thinkdeeptech/deep-microservice-configuration:latest .
            working_directory: ./packages/deep-microservice-configuration
        - run: docker push thinkdeeptech/deep-microservice-configuration:${CIRCLE_BUILD_NUM}
        - run: docker push thinkdeeptech/deep-microservice-configuration:latest
        - helm/install-helm-client:
            version: v3.7.2
        - run:
            name: Download project dependencies
            command: helm dependency update
            working_directory: ./packages/deep-microservice-configuration
        - helm/upgrade-helm-chart:
            chart: "./packages/deep-microservice-configuration"
            helm-version: "v3.7.2"
            namespace: "default"
            recreate-pods: true
            release-name: "deep-microservice-configuration-latest"
            values-to-override: "mongodb.auth.rootUser=$MONGODB_USERNAME,mongodb.auth.rootPassword=$MONGODB_ROOT_PASSWORD,namespace=default,nodeEnv=$NODE_ENV"
            update-repositories: true
            wait: true

    build_and_deploy_microservice_gateway:
      docker:
        - image: 'cimg/base:stable'

      working_directory: ~/project

      steps:
        - checkout
        - setup_remote_docker:
            version: 20.10.7
        - login_docker
        - k8s/install
        - k8s/initialize:
            cluster: predecos-kubernetes-cluster
        - run:
            command: docker build -t thinkdeeptech/deep-microservice-gateway:${CIRCLE_BUILD_NUM} -t thinkdeeptech/deep-microservice-gateway:latest .
            working_directory: ./packages/deep-microservice-gateway
        - run: docker push thinkdeeptech/deep-microservice-gateway:${CIRCLE_BUILD_NUM}
        - run: docker push thinkdeeptech/deep-microservice-gateway:latest
        - helm/install-helm-client:
            version: v3.7.2
        - run:
            name: Download project dependencies
            command: helm dependency update
            working_directory: ./packages/deep-microservice-gateway
        - helm/upgrade-helm-chart:
            chart: "./packages/deep-microservice-gateway"
            helm-version: "v3.7.2"
            namespace: "default"
            recreate-pods: true
            release-name: "deep-microservice-gateway-latest"
            values-to-override: "auth.audience=$PREDECOS_AUTH_AUDIENCE,auth.jwksUri=$PREDECOS_AUTH_JWKS_URI,auth.issuer=$PREDECOS_AUTH_ISSUER,microservice.analysis.url=$PREDECOS_MICROSERVICE_ANALYSIS_URL,microservice.collection.url=$PREDECOS_MICROSERVICE_COLLECTION_URL,microservice.configuration.url=$PREDECOS_MICROSERVICE_CONFIGURATION_URL,replicas=1,namespace=default,nodeEnv=$NODE_ENV"
            update-repositories: true
            wait: true

    build_and_deploy_microservice_subscription:
      docker:
        - image: 'cimg/base:stable'

      working_directory: ~/project

      steps:
        - checkout
        - setup_remote_docker:
            version: 20.10.7
        - login_docker
        - k8s/install
        - k8s/initialize:
            cluster: predecos-kubernetes-cluster
        - run:
            command: docker build -t thinkdeeptech/deep-microservice-subscription:${CIRCLE_BUILD_NUM} -t thinkdeeptech/deep-microservice-subscription:latest .
            working_directory: ./packages/deep-microservice-subscription
        - run: docker push thinkdeeptech/deep-microservice-subscription:${CIRCLE_BUILD_NUM}
        - run: docker push thinkdeeptech/deep-microservice-subscription:latest
        - helm/install-helm-client:
            version: v3.7.2
        - run:
            name: Download project dependencies
            command: helm dependency update
            working_directory: ./packages/deep-microservice-subscription
        - helm/upgrade-helm-chart:
            chart: "./packages/deep-microservice-subscription"
            helm-version: "v3.7.2"
            namespace: "default"
            recreate-pods: true
            release-name: "deep-microservice-subscription-latest"
            values-to-override: "auth.audience=$PREDECOS_AUTH_AUDIENCE,auth.jwksUri=$PREDECOS_AUTH_JWKS_URI,auth.issuer=$PREDECOS_AUTH_ISSUER,kafka.host=$PREDECOS_KAFKA_HOST,kafka.port=$PREDECOS_KAFKA_PORT,microservice.analysis.url=$PREDECOS_MICROSERVICE_ANALYSIS_URL,microservice.collection.url=$PREDECOS_MICROSERVICE_COLLECTION_URL,microservice.configuration.url=$PREDECOS_MICROSERVICE_CONFIGURATION_URL,replicas=1,namespace=default,nodeEnv=$NODE_ENV"
            update-repositories: true
            wait: true

    build_ui:
      docker:
          - image: 'cimg/node:14.17.6'

      working_directory: ~/project

      steps:
          - run:
              name: Update repositories
              command: sudo apt-get update
          - run:
              name: Install firefox dependency (take this out when browser-tools orb is fixed)
              command: sudo apt-get install -y libasound-dev
          - browser-tools/install-browser-tools
          - checkout
          - install_monorepo
          - test_monorepo
          - build_ui_command


    deploy_kafka:
      docker:
        - image: 'cimg/base:stable'

      working_directory: ~/project

      steps:
        - checkout
        - setup_remote_docker:
            version: 20.10.7
        - login_docker
        - k8s/install
        - k8s/initialize:
            cluster: predecos-kubernetes-cluster
        - helm/install-helm-client:
            version: v3.7.2
        - run:
            name: Add Bitnami Repository
            command: helm repo add bitnami https://charts.bitnami.com/bitnami
        - helm/upgrade-helm-chart:
            chart: "bitnami/kafka"
            version: "15.1.0"
            helm-version: "v3.7.2"
            recreate-pods: true
            release-name: "kafka-latest"
            reuse-values: true
            update-repositories: true

    deploy_ui:
      docker:
          - image: 'cimg/node:14.17.6'

      working_directory: ~/project

      steps:
          - checkout
          - install_monorepo
          - build_ui_command
          - deploy_ui_command


workflows:

  version: 2

  build_and_deploy_if_master:

    jobs:

      - deploy_kafka:
          filters:
            branches:
              only: master

      - build_and_deploy_microservice_collection:
          requires:
            - deploy_kafka
          filters:
            branches:
              only: master

      - build_and_deploy_microservice_analysis:
          requires:
            - build_and_deploy_microservice_collection
            - deploy_kafka
          filters:
            branches:
              only: master

      - build_and_deploy_microservice_configuration:
          filters:
            branches:
              only: master

      - build_and_deploy_microservice_gateway:
          requires:
            - build_and_deploy_microservice_collection
            - build_and_deploy_microservice_analysis
            - build_and_deploy_microservice_configuration
          filters:
            branches:
              only: master

      - build_and_deploy_microservice_subscription:
          requires:
            - build_and_deploy_microservice_collection
            - build_and_deploy_microservice_analysis
            - build_and_deploy_microservice_configuration
            - deploy_kafka
          filters:
            branches:
              only: master

      - build_ui

      - deploy_ui:
          requires:
            - build_and_deploy_microservice_gateway
            - build_and_deploy_microservice_subscription
            - build_ui
          filters:
            branches:
              only: master
