version: 2
jobs:
    build:
        docker:
            - image: circleci/node:9.10

        working_directory: ~/repo

        steps:
            - checkout

            - save_cache:
                paths:
                    - null
                key: v1-dependencies-{{ checksum "package.json" }}

            # Download and cache dependencies
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}

            - run: yarn run setup

            - run: yarn run test