version: 2.1

orbs:
    browser-tools: circleci/browser-tools@1.2.2

commands:
    install:
      steps:
        - run:
          name: Installing Dependencies
          command: yarn install
        - run:
          name: Adding Missing Dependencies
          command: yarn add -W apollo-datasource-mongodb && yarn add -W mongodb

    test:
      steps:
        - run:
          name: Run Tests
          command: yarn run tests

    build:
      steps:
        - run:
          name: Perform Build
          command: yarn run build

    deploy:
      steps:
        - run:
          name: Installing Firebase
          command: curl -sL https://firebase.tools | bash

        - run:
            name: Performing Deployment
            command: firebase --token $FIREBASE_TOKEN deploy



jobs:
    build:
      docker:
          - image: 'cimg/node:14.17.6'

      working_directory: ~/project

      steps:

          - install

          - test

          - build

    deploy:
      docker:
          - image: 'cimg/node:14.17.6'

      working_directory: ~/project

      steps:

          - install

          - build

          - deploy


workflows:

  version: 2

  build:
    jobs:
      - install
      - test:
        requires:
          - install
      - build:
        requires:
          - install

  deploy:
    jobs:
      - build

      - deploy:
        requires:
          - build

        filters:
          branches:
            only:
              master

# jobs:
#     deploy:
#         docker:
#             - image: 'cimg/node:14.17.6'

#         working_directory: ~/repo

#         steps:

#             - checkout

#             - run: yarn install --force

#             - run: yarn run build

#             - run: curl -sL https://firebase.tools | bash

#             - run: which firebase

#             - run: firebase --token $FIREBASE_TOKEN deploy

#     build:
#         docker:
#             - image: 'cimg/node:14.17.6-browsers'

#         working_directory: ~/repo

#         steps:
#             - browser-tools/install-browser-tools

#             - checkout

#             - run: node --version

#             - run: yarn --version

#             - run: yarn install --force

#             # TODO: There's something wrong with the yarn install above. It seems to avoid installation of apollo-datasource-mongodb as
#             # well as mongodb itself. This is a patch solution, but isn't scalable. After build fix, troubleshoot.
#             - run: yarn add -W apollo-datasource-mongodb

#             - run: yarn add -W mongodb

#             - run: yarn run tests

#             - run: yarn run build

# workflows:

#   version: 2

#   deploy:

#     jobs:

#       - build

#       - deploy:

#           requires:

#             - build

#           filters:

#             branches:

#               only: master