version: 2.1
orbs:
    browser-tools: circleci/browser-tools@1.2.2
jobs:
    build:
        docker:
            - image: 'cimg/node:14.17.6-browsers'

        working_directory: ~/repo

        steps:
            - browser-tools/install-browser-tools

            - checkout

            - save_cache:
                paths:
                    - ""
                key: v1-dependencies-{{ checksum "package.json" }}

            # Download and cache dependencies
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}

            - run: sudo apt-get install python3

            - run: sudo apt-get install python3-pip

            - run: sudo pip3 install pytest

            - run: alias python=python3

            - run: node --version

            - run: yarn --version

            - run: yarn install

            - run: yarn run tests

            - run: yarn run build

            - run: curl -sL https://firebase.tools | bash

            - run: which firebase

            - run: firebase --token $FIREBASE_TOKEN login:ci

            - run: firebase deploy