version: 2.1
orbs:
    browser-tools: circleci/browser-tools@1.2.2
jobs:
    deploy:
        docker:
            - image: 'cimg/node:14.17.6'

        working_directory: ~/repo

        steps:

            - checkout

            - run: yarn install

            - run: yarn run build

            - run: curl -sL https://firebase.tools | bash

            - run: which firebase

            - run: firebase --token $FIREBASE_TOKEN deploy

    build:
        docker:
            - image: 'cimg/node:14.17.6-browsers'

        working_directory: ~/repo

        steps:
            - browser-tools/install-browser-tools

            - checkout

            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}

            # Download and cache dependencies
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}

            - run: node --version

            - run: yarn --version

            - run: yarn install

            - run: yarn run tests

            - run: yarn run build

workflows:

  version: 2

  deploy:

    jobs:

      - build

      - deploy:

          requires:

            - build

          filters:

            branches:

              only: master