  global:
    nodeEnv: "development"
    docker:
      secretName: ""

  graphql:
    path: "/graphql"
    port: "4003"

  replicas: 1

  container:
    image: "thinkdeeptech/deep-microservice-configuration:latest"

  configurationmongodb:
    auth:
      enabled: false
      rootUser: "root"
      rootPassword: ""
