  global:
    nodeEnv: "development"

  graphql:
    path: "/graphql"
    port: 4003

  replicas: 1

  configurationmongodb:
    auth:
      enabled: false
      rootUser: "root"
      rootPassword: ""
