apiVersion: "v1"
kind: "ConfigMap"
metadata:
    name: {{ printf "%s-config-map" .Release.Name | quote}}
data:
    NODE_ENV: {{ required "A valid node environment is required" .Values.nodeEnv | quote}}