apiVersion: "v1"
kind: "Secret"
metadata:
    name: {{ printf "%s-secrets" .Release.Name | quote }}
data:
    PREDECOS_MONGODB_CONNECTION_STRING: {{ printf "mongodb://%s:%s@%s.%s.svc.cluster.local" (required "The user name for MongoDB is required" .Values.mongodb.username) (required "The user password for MongoDB is required" .Values.mongodb.password) (.Release.Name) (.Values.namespace) | b64enc | quote}}