apiVersion: "v1"
kind: "Secret"
metadata:
    name: {{ printf "%s-deep-microservice-analysis-secrets" .Release.Name | quote }}
    namespace: {{ .Release.Namespace | quote }}
data:
    {{ if not .Values.global.kafka.secretName }}
        PREDECOS_KAFKA_HOST: {{ printf "%s" (required "A valid Kafka host is required if a secret name is not specified." .Values.global.kafka.host) | b64enc | quote}}
        PREDECOS_KAFKA_PORT: {{ printf "%d" (required "A valid kafka port is required if a secret name is not specified." .Values.global.kafka.port) | b64enc }}
    {{ end }}
    PREDECOS_MONGODB_CONNECTION_STRING: {{ printf "mongodb://%s-analysisMongoDB.%s.svc.cluster.local" (.Release.Name) (.Release.Namespace) | b64enc | quote}}