apiVersion: "v1"
kind: "Secret"
metadata:
    name: {{ printf "%s-deep-microservice-analysis-secrets" .Release.Name | quote }}
    namespace: {{ .Release.Namespace | quote }}
data:
    {{ if not .Values.global.kafka.secretName }}
    PREDECOS_KAFKA_HOST: {{ printf "%s" (required "A valid Kafka host is required if a secret name is not specified." .Values.global.kafka.host) | b64enc | quote}}
    PREDECOS_KAFKA_PORT: {{ printf "%d" (required "A valid kafka port is required if a secret name is not specified." .Values.global.kafka.port) | b64enc }}
    {{ end }}
    MICROSERVICE_ANALYSIS_NEO4J_URL: {{ printf "bolt+s://%s:7687" (required "A valid neo4j advertised address is required." (index .Values "neo4j" "config" "dbms.default_advertised_address")) | b64enc | quote }}
    MICROSERVICE_ANALYSIS_NEO4J_USERNAME: {{ printf "%s" (required "A valid neo4j username is required." .Values.neo4j.neo4j.username) | b64enc | quote }}
    MICROSERVICE_ANALYSIS_NEO4J_PASSWORD: {{ printf "%s" (required "A valid neo4j user password is required." .Values.neo4j.neo4j.password) | b64enc | quote }}
    MICROSERVICE_ANALYSIS_NEO4J_DATABASE: {{ printf "%s" (required "A valid neo4j database is required." .Values.neo4j.config.dbms.default_database) | b64enc | quote }}
    PREDECOS_MONGODB_CONNECTION_STRING: {{ printf "mongodb://%s-analysismongodb.%s.svc.cluster.local" (.Release.Name) (.Release.Namespace) | b64enc | quote}}