apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
  labels:
    app: zookeeper
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: bitnami/zookeeper:latest
        ports:
        - containerPort: $PREDECOS_ZOOKEEPER_PORT
        env:
          - name: ALLOW_ANONYMOUS_LOGIN
            value: "$ZOOKEEPER_ALLOW_ANONYMOUS_LOGIN"
