  global:
    namespace: "default"
    nodeEnv: "development"

  replicas: 1

  graphql:
    port: 4002
    path: "/graphql"

  mongodb:
    auth:
      enabled: false
      rootUser: "root"
      rootPassword: ""

  kafka:
    host: ""
    port: 9092

  twitter:
    bearer: ""
