  global:
    nodeEnv: "development"
    kafka:
      secretName: ""
      host: ""
      port: "9092"
    docker:
      secretName: ""

  graphql:
    port: "4001"
    path: "/graphql"

  replicas: 1

  container:
    image: "thinkdeeptech/deep-microservice-analysis:latest"

  analysismongodb:
    auth:
      enabled: false
      rootUser: "root"
      rootPassword: ""

  neo4j:
    name: "analysisneo4j"
    resources:
      cpu: "0.5"
      memory: "8Gi"

    password: ""
    volumes:
      data:
        mode: "volumeClaimTemplate"
        volumeClaimTemplate:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: "8Gi"
          storageClassName: "do-block-storage"

    services:
      neo4j:
        enabled: false
        annotations:
          service.beta.kubernetes.io/do-loadbalancer-certificate-id: ""