  global:
    nodeEnv: "development"
    kafka:
      secretName: ""
      host: ""
      port: "9092"
    docker:
      secretName: ""

  graphql:
    port: "4001"
    path: "/graphql"

  replicas: 1

  container:
    image: "thinkdeeptech/deep-microservice-analysis:latest"

  analysismongodb:
    auth:
      enabled: false
      rootUser: "root"
      rootPassword: ""

  neo4j:
    resources:
      cpu: "0.5"
      memory: "8Gi"

    password: ""
    volumes:
      metadata:
        name: "analysis-neo4j-storage"
      data:
        mode: "defaultStorageClass"
        defaultStorageClass:
          requests:
            storage: "8Gi"