  global:
    nodeEnv: "development"
    kafka:
      secretName: ""
      host: ""
      port: "9092"
    docker:
      secretName: ""

  graphql:
    port: "4001"
    path: "/graphql"

  replicas: 1

  container:
    image: "thinkdeeptech/deep-microservice-analysis:latest"

  analysismongodb:
    auth:
      enabled: false
      rootUser: "root"
      rootPassword: ""

  neo4j:
    resources:
      cpu: "0.5"
      memory: "8Gi"

    password: ""
    volumes:
      data:
        mode: "volumeClaimTemplate"
        volumeClaimTemplate:
          metadata:
            name: analysis-neo4j-pvc
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 8Gi
          storageClassName: do-block-storage