  global:
    nodeEnv: "development"
    kafka:
      secretName: ""
      host: ""
      port: 9092

  graphql:
    port: 4001
    path: "/graphql"

  replicas: 1

  analysisMongoDB:
    auth:
      enabled: false
      rootUser: "root"
      rootPassword: ""