  global:
    nodeEnv: "development"
    kafka:
      secretName: ""
      host: ""
      port: "9092"
    docker:
      secretName: ""

  graphql:
    port: "4001"
    path: "/graphql"

  replicas: 1

  container:
    image: "thinkdeeptech/deep-microservice-analysis:latest"

  analysismongodb:
    auth:
      enabled: false
      rootUser: "root"
      rootPassword: ""

  analysisneo4j:
    resources:
      cpu: "0.5"
      memory: "20Gi"

    password: ""

  volumes:
    mode: "defaultStorageClass"
    data:
      mode: "defaultStorageClass"
      defaultStorageClass:
        requests:
          storage: "20Gi"
