apiVersion: "rbac.authorization.k8s.io/v1"
kind: "Role"
metadata:
    namespace: {{ .Release.Namespace | quote }}
    name: {{ printf "%s-collection-manager-role" .Release.Name | quote }}
rules:
    - apiGroups: ["", "batch"]
      resources:
          - "cronjobs"
          - "jobs"
      verbs:
          - "create"
          - "delete"
          - "get"
          - "list"
    - apiGroups: ["apps", "extensions"]
      resources:
          - "deployments"
      verbs:
          - "list"
          - "get"
