apiVersion: "v1"
kind: "ConfigMap"
metadata:
    name: {{ printf "%s-deep-microservice-collection-config-map" .Release.Name | quote }}
    namespace: {{ .Release.Namespace | quote }}
data:
    DEPLOYMENT_NAME: {{ printf "%s-deep-microservice-collection-deployment" .Release.Name | quote }}
    GRAPHQL_PORT: {{ required "A valid port at which the application can be accessed is required" .Values.graphql.port | quote }}
    GRAPHQL_PATH: {{ required "A valid path at which the application can be accessed is required (i.e, /graphql)" .Values.graphql.path | quote}}
    NAMESPACE: {{ .Release.Namespace | quote }}
    DATA_COLLECTOR_IMAGE_NAME: {{ required "A valid data collection image is required (i.e, thinkdeeptech/collect-data:latest)." .Values.data.collector.image | quote }}
    HELM_RELEASE_NAME: {{ .Release.Name | quote }}
    NODE_ENV: {{ required "A valid node environment is required" .Values.global.nodeEnv | quote}}