
apiVersion: "v1"
kind: "Secret"
metadata:
    name: {{ printf "%s-deep-microservice-collection-secret" .Release.Name | quote }}
    namespace: {{ .Values.global.namespace | quote }}
data:
    PREDECOS_KAFKA_HOST: {{ printf "%s" (required "A valid Kafka host is required." .Values.global.kafka.host) | b64enc | quote}}
    PREDECOS_KAFKA_PORT: {{ printf "%d" (required "A valid kafka port is required." .Values.global.kafka.port) | b64enc }}
    PREDECOS_MONGODB_CONNECTION_STRING: {{ printf "mongodb://%s-mongodb.%s.svc.cluster.local" (.Release.Name) (.Values.global.namespace) | b64enc | quote}}
    PREDECOS_TWITTER_BEARER: {{ printf "%s" (required "A twitter api bearer token is required." .Values.twitter.bearer) | b64enc | quote }}