apiVersion: "rbac.authorization.k8s.io/v1"
kind: "Role"
metadata:
    namespace: {{ .Values.namespace | quote }}
    name: {{ printf "%s-secret-accessor-role" .Release.Name | quote }}
rules:
    - apiGroups: [""]
      resources:
          - "secrets"
      verbs:
          - "get"
          - "list"