apiVersion: "v1"
kind: "Secret"
metadata:
    name: {{ printf "%s-secrets" .Release.Name | quote }}
data:
    PREDECOS_KAFKA_HOST: {{ printf "%s" (required "A valid Kafka host is required." .Values.kafka.host) | b64enc | quote}}
    PREDECOS_KAFKA_PORT: {{ printf "%d" (required "A valid kafka port is required." .Values.kafka.port) | b64enc }}
    # TODO
    # PREDECOS_MONGODB_CONNECTION_STRING: {{ printf "mongodb://%s:%s@%s-mongodb.%s.svc.cluster.local" (required "The user name for MongoDB is required" .Values.mongodb.auth.rootUser) (required "The user password for MongoDB is required" .Values.mongodb.auth.rootPassword) (.Release.Name) (.Values.namespace) | b64enc | quote}}
    PREDECOS_MONGODB_CONNECTION_STRING: {{ printf "mongodb://%s-mongodb.%s.svc.cluster.local" (.Release.Name) (.Values.namespace) | b64enc | quote}}
    PREDECOS_TWITTER_BEARER: {{ printf "%s" (required "A twitter api bearer token is required." .Values.twitter.bearer) | b64enc | quote }}