# apiVersion: "v1"
# kind: "Service"
# metadata:
#   name: {{ printf "%s-service" .Release.Name | quote }}
# spec:
#   selector:
#     app: deep-microservice-collection
#   ports:
#     - protocol: TCP
#       port: 4002